
services:     

  app:
    profiles: 
      - app
    build:
      context: .
      target: development   
    volumes:
        - ./:/home/node/app
    ports:
      - '7010:7010'
    command: >
        sh -c "
        yarn install &&
        yarn dev --host"
    env_file: .env.docker